[package]
name = "highs-example-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
highs = "2.0.0"
polars = {version = "0.53.0", features = ["lazy", "csv"]}
serde = {version = "1.0.202", features = ["derive"]}
toml = "1.0.2"
